"""Modified user table and drop jwt table

Revision ID: d7e05f49f340
Revises: 8a787fbb66d1
Create Date: 2023-05-07 18:21:09.012145

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7e05f49f340"
down_revision = "8a787fbb66d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_jwt", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_jwt_refresh_jti")

    op.drop_table("refresh_jwt")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=False,
                comment="Признак активного пользователя",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                nullable=False,
                comment="Признак верефицированного пользователя",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_admin",
                sa.Boolean(),
                nullable=False,
                comment="Признак администратора",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_admin")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_active")

    op.create_table(
        "refresh_jwt",
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор refresh jwt токена",
        ),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "refresh_jti", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_refresh_jwt_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_jwt"),
    )
    with op.batch_alter_table("refresh_jwt", schema=None) as batch_op:
        batch_op.create_index(
            "ix_refresh_jwt_refresh_jti", ["refresh_jti"], unique=False
        )

    # ### end Alembic commands ###
